version: '3'

services:
  # Frontend Service
  mysite: # name of service
    build: mysite # dir of dockerfile
    restart: unless-stopped
    tty: true
    ports:
    - "8084:80" # map ports
    networks:
    - app-network

  # Nginx Service
  mysite-webserver:
    image: nginx:alpine
    container_name: mysite-webserver
    restart: unless-stopped
    tty: true
    ports:
    - "82:80" # for me locally
    - "446:443"
    networks:
    - app-network

# Networks
networks:
  app-network:
    driver: bridge
