version: '3'

services:
  # Frontend Service
  vue: # name of service
    build: frontend # dir of dockerfile
    restart: unless-stopped
    tty: true
    ports:
    - "8082:80" # map ports
    networks:
    - app-network

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
    - "82:80" # for me locally
    - "444:443"
    networks:
    - app-network

# Networks
networks:
  app-network:
    driver: bridge
